Дипломный проект, который я сдам фиг знает когда
qwerty-yhn/java-explore-with-me pull request #3
Opened 2023-04-26 16:17 UTC by qwerty-yhn

Сергей привет)

2023-04-27 06:56 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, давай обсудим поправим и будет зачет =)

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
Модификаторы доступа

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-service/src/main/resources/shema.sql
> +create table if not exists endpoint
Не говорю переделывать, но рекомендую ознакомиться с такой идеей оформления:
```
CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(150) NOT NULL,
  CONSTRAINT pk_aps PRIMARY KEY (id),
  CONSTRAINT UQ_APPS_NAME UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app_id BIGINT NOT NULL,
  uri VARCHAR(2048),
  ip VARCHAR(15) NOT NULL,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_endpoint_hit PRIMARY KEY (id),
  CONSTRAINT FK_ENDPOINT_HIT_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id)
);
```

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-client/src/main/java/ru/practicum/evm/StatisticClient.java
> +//    public ResponseEntity<Object> createHit(EndpointHitDto endpointHitDto) {
Почему закомментировано?

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +    String timestamp;
Почему так нельзя?
```
 @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")
    private LocalDateTime timestamp;
```

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/ViewStatsDto.java
> +public class ViewStatsDto {
Модификаторы доступа

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
id поле тут не должно быть? (уточняю)

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-service/src/main/java/ru/practicum/evm/EndpointHitController.java
> +    public List<ViewStatsDto> getStats(@RequestParam("start") @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
"yyyy-MM-dd HH:mm:ss" - зачем дублируем

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-service/src/main/java/ru/practicum/evm/model/EndpointHit.java
> +    private LocalDateTime timestamp;
@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd HH:mm:ss")

2023-04-27 06:56 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +    String timestamp;
Наверно тут можно и без этого тк есть EndpointHit

2023-04-27 15:03 UTC, qwerty-yhn commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +public class EndpointHitDto {
А там  в swaggere показывает какие нужны поля, я их и вписал) честно говоря не экперементировал, будет работать или нет)

2023-04-27 15:05 UTC, qwerty-yhn commented on ewm-statistic/ewm-statistic-service/src/main/resources/shema.sql
> +create table if not exists endpoint
Сохранил) спасибо)

2023-04-27 15:07 UTC, qwerty-yhn commented on ewm-statistic/ewm-statistic-client/src/main/java/ru/practicum/evm/StatisticClient.java
> +//    public ResponseEntity<Object> createHit(EndpointHitDto endpointHitDto) {
Это из sharait часть, я от туда все дернул) но не понял где применить клиента и закоментил)

2023-04-27 15:14 UTC, qwerty-yhn commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +    String timestamp;
Поправил) с этим параметром временем это вообще боль(((((

2023-04-27 15:18 UTC, qwerty-yhn commented on ewm-statistic/ewm-statistic-service/src/main/java/ru/practicum/evm/EndpointHitController.java
> +    public List<ViewStatsDto> getStats(@RequestParam("start") @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
Поправил

2023-04-27 15:56 UTC, qwerty-yhn commented on ewm-statistic/ewm-statistic-dto/src/main/java/ru/practicum/dto/EndpointHitDto.java
> +    String timestamp;
Не много помучился без @NoArgsConstructor
@AllArgsConstructor JsonFormat не работает

2023-04-28 04:54 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет

2023-04-28 04:54 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-service/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
`<version>${project.version}</version>`

2023-04-28 04:54 UTC, krylov-sergey-sergeevich commented on ewm-statistic/ewm-statistic-service/src/main/java/ru/practicum/evm/EndpointHitController.java
> +    private final String dataParent = "yyyy-MM-dd HH:mm:ss";
лучше вынести в DateUtils класс

2023-06-06 17:01 UTC, merged